"""Thin wrapper around the abc2ly binary.

abc2ly (shipped with LilyPond) converts ABC notation to a .ly file that
contains a \header, a named \voicedefault music variable, and a \score
block. For our hymnal pipeline we only want the MUSIC BODY -- the note
stream inside that \voicedefault variable -- because we build our own
\book / \bookpart preamble and supply a separate chord-overlay voice.

Public API:
    abc_to_lilypond(abc: str) -> str
        Returns the LilyPond music body (everything between the opening
        brace of voicedefault and the matching closing brace), without
        the \set / \time / \key lines we will override in the parent
        \score.

ASCII-only source. python3.10.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile


ABC2LY_BIN = "abc2ly"


def _run_abc2ly(abc: str) -> str:
    """Run abc2ly on `abc` and return the generated .ly source text."""
    with tempfile.TemporaryDirectory() as td:
        abc_path = os.path.join(td, "in.abc")
        out_stem = os.path.join(td, "out")
        with open(abc_path, "w", encoding="utf-8") as fh:
            fh.write(abc)
        try:
            subprocess.run(
                [ABC2LY_BIN, abc_path, "-o", out_stem, "-q"],
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
        except FileNotFoundError:
            raise RuntimeError(
                "abc2ly not found on PATH; install lilypond")
        except subprocess.CalledProcessError as exc:
            sys.stderr.write(exc.stderr.decode("utf-8", "replace"))
            raise RuntimeError("abc2ly failed") from exc

        # abc2ly writes to exactly out_stem (no extension) in 2.22.
        for candidate in (out_stem, out_stem + ".ly"):
            if os.path.exists(candidate):
                with open(candidate, "r", encoding="utf-8") as fh:
                    return fh.read()
        raise RuntimeError(
            "abc2ly produced no output file for stem %r" % out_stem)


def _extract_voice_body(ly_src: str) -> str:
    """Return the music body (notes + annotations) from a voicedefault block.

    The abc2ly output pattern is:

        voicedefault =  {
        \set Score.defaultBarType = ""
        \time 4/4 \key g \major <notes...>
        }

    We grab everything between the first `{` after `voicedefault` and the
    matching `}`. We strip the leading \set/\time/\key directives because
    the outer \score supplies its own time/key.
    """
    marker = "voicedefault"
    idx = ly_src.find(marker)
    if idx < 0:
        raise RuntimeError("voicedefault block not found in abc2ly output")
    brace_open = ly_src.find("{", idx)
    if brace_open < 0:
        raise RuntimeError("no '{' after voicedefault")

    depth = 0
    i = brace_open
    end = -1
    while i < len(ly_src):
        c = ly_src[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                end = i
                break
        i += 1
    if end < 0:
        raise RuntimeError("unbalanced braces in voicedefault block")

    body = ly_src[brace_open + 1:end]
    return body.strip()


def abc_to_lilypond(abc: str) -> str:
    """Return the LilyPond music body generated by abc2ly, without headers.

    Example (input is ABC 'X:1\\nT:T\\nM:4/4\\nL:1/4\\nK:G\\n|G2D2|'):
    returns a string like
        '\\set Score.defaultBarType = ""\\n\\time 4/4 \\key g \\major'
        '   g\\'2    d\\'2    \\bar "|"  '
    """
    raw = _run_abc2ly(abc)
    return _extract_voice_body(raw)


if __name__ == "__main__":
    demo = (
        "X: 1\n"
        "T: Demo\n"
        "M: 4/4\n"
        "L: 1/4\n"
        "K: G\n"
        '"^G"D G B d | "^C"c2 "^D7"d2 |\n'
    )
    print(abc_to_lilypond(demo))
